# Book settings
title: Think Bayes
author: Allen B. Downey

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/AllenDowney/ThinkBayes2
html:
  use_repository_button: true

parse:
  myst_extended_syntax: true
